// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoCBpfPfhUsOWhhGVPGqe4GY1QRaxE8Q',
    appId: '1:1031354240085:web:f098b468e3030ee79058dc',
    messagingSenderId: '1031354240085',
    projectId: 'vote-app-cc87c',
    authDomain: 'vote-app-cc87c.firebaseapp.com',
    storageBucket: 'vote-app-cc87c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDWZ_bwOm-1uB-7YhTsyz8hkDYBquHLd0',
    appId: '1:1031354240085:android:756c793f85f90a7b9058dc',
    messagingSenderId: '1031354240085',
    projectId: 'vote-app-cc87c',
    storageBucket: 'vote-app-cc87c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvtu8XKbNiunv5q0GglMo5o45xR6dVUk4',
    appId: '1:1031354240085:ios:e40613ef156fdd759058dc',
    messagingSenderId: '1031354240085',
    projectId: 'vote-app-cc87c',
    storageBucket: 'vote-app-cc87c.appspot.com',
    iosClientId: '1031354240085-micpaauln6o4l2l8nis0b67339qs1ja8.apps.googleusercontent.com',
    iosBundleId: 'com.example.webPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvtu8XKbNiunv5q0GglMo5o45xR6dVUk4',
    appId: '1:1031354240085:ios:e40613ef156fdd759058dc',
    messagingSenderId: '1031354240085',
    projectId: 'vote-app-cc87c',
    storageBucket: 'vote-app-cc87c.appspot.com',
    iosClientId: '1031354240085-micpaauln6o4l2l8nis0b67339qs1ja8.apps.googleusercontent.com',
    iosBundleId: 'com.example.webPrototype',
  );
}
